sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/New Folder With Items/IMG_7617.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/BI0018.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/New Folder With Items/16067173277485a455873c440d10e91587c1a400dc_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0064.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/New Folder With Items/IMG_7723.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de abajo/163066319078f8270651665c7bcb3432cab265672c_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/B0034.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/New Folder With Items/IMG_7676.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/1626836500131f7da89bfa532087a1963a68495b22_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/BI0011.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/New Folder With Items/IMG_7615.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/New Folder With Items/IMG_7673.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/V0079_2.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/New Folder With Items/1632706599c2ddc376394482b720021106e31919ed_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/BI0029.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/16268364979da6e87032a85dd64c07cd12cba5d505_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/New Folder With Items/IMG_7679.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/New Folder With Items 2/16626228592156c4b77c051c008d16c6f1e540035e_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0089.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/V0069_1.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/BI0013.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de abajo/165292360889ed716f906c3977313f8e02199b3dc5_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/New Folder With Items/IMG_3111.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/PA0001.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/New Folder With Items/IMG_7675.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/V0089_2.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/V0079_1.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/BI0007.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0019.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/New Folder With Items/162544710062ad388e9212b3b1d7818b2f965f8c45_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/New Folder With Items/IMG_7817.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/1654053773795e0e11b7478327ffb77bf9c1978f38_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/T0020.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/T0025.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/New Folder With Items/IMG_7680.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/New Folder With Items/IMG_7619.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0056.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/V0082_1.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0063.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/New Folder With Items/IMG_7597.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/New Folder With Items/162487326523c65935802a27426c99bdc5298920bf_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/New Folder With Items/16340032657c4f01a8235a1b50f104c443f0e217e4_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/New Folder With Items/161542586840c6fede951cfda50d0912fea708102c.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/New Folder With Items 2/16612189393f1e844613da39c4e7e3062727676c2f_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Calzado/New Folder With Items/1536743545451394145_thumbnail_900x1199.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/New Folder With Items/o.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/B0021.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/New Folder With Items/IMG_7707.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/New Folder With Items/IMG_7627.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/New Folder With Items/IMG_7634.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/BI0010.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Bolsos/A0010.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/New Folder With Items 2/16702235721a056dfa513224b85bd220fac054257b_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/163901492047faec4f6e0a508ffc7441c301321f1d_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/B0035.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/New Folder With Items 2/16612189405bb4ef72e9441b414851c97c49f1ee64_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/New Folder With Items 2/16702235777d7c08fde68d52ac9cc08a72171201f0_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/164490651841746b8fe61f49c97ee9554cece6fb5c_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/BI0006.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Jumpsuit/J0004.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Calzado/CA0002.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/New Folder With Items/IMG_7609.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Bolsos/New Folder With Items/15900350026ac3a672cddc595f24c24dbe676caca1_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/1639014925f74b80e01b520721069b6cc921b24dda_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/1647481180ae7ce59ae9c78ae21b7bcd94c26a9e69_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/T0007.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0070.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/New Folder With Items/c8e6f835-7c01-4ae5-82ce-5bdbcda5bf52.JPG"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0032.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/T0013.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0009.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Bolsos/A0008.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/B0011.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/T0024.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/T0019.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0004.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/New Folder With Items/IMG_7602.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/New Folder With Items/1632706597a588a213ec0b963323b7033a1fddc4cd_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/B0038.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Bolsos/New Folder With Items/1660209998f14a04f6c8eb145778464e263baa48ea_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0003.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/BI0002.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño niñas/TN001.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0001.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0045.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/BI0004.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0034.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/B0001.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/New Folder With Items/IMG_0579.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Calzado/New Folder With Items/1615264514db988f174f40c9f468ee28f3206ce9d2_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/V0045_1.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/New Folder With Items/IMG_7599.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/New Folder With Items/IMG_7593.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño niñas/TN009.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño niñas/TN008.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/New Folder With Items/IMG_0580.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Conjuntos/IMG_7140.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0002.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0015.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño niñas/TN007.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño niñas/TN006.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0124.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño niñas/TN003.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/IMG_7060.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/IMG_7060 2.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/New Folder With Items/IMG_7064.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/B0005.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/B0006.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/IMG_7068 2.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/IMG_7069 2.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/B0007.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0016.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Jumpsuit/IMG_7113.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/IMG_7071 2.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/IMG_7073 2.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/New Folder With Items/IMG_7074.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/B0015.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Conjuntos/C0007.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/New Folder With Items/IMG_7076.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0014.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0013.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Conjuntos/IMG_7145.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0012.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/B0016 .jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/162494985646a3c19e94bdd2d817c17e65de70bfdb_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/New Folder With Items/IMG_7082.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/New Folder With Items/IMG_7648.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/B0008.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/T0040.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/B0012.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/New Folder With Items/Screenshot 2023-04-25 at 11.06.33.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/New Folder With Items/IMG_7086.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0028.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0046.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0027.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/New Folder With Items/IMG_7607.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0026.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/B00156.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/B0018.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Jumpsuit/J0005.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/B0017.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/New Folder With Items/IMG_7089.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/IMG_7090 2.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/IMG_7120.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0035.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/New Folder With Items/IMG_7093.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/B0010.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/IMG_7094 2.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0022.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0020.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/IMG_7096 2.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/IMG_7100 2.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/B00098.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0025.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/B0009.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Jumpsuit/J0002.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0023.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0021.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/IMG_7099 2.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Conjuntos/IMG_7122.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0039.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0024.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/New Folder With Items/IMG_7102.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0029.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/New Folder With Items 2/1647393753d12e03ca43af07faac1bec47f2bbe402_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/New Folder With Items/IMG_7105.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/B0014.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/B0013.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Bolsos/New Folder With Items/16191596347b2115e16d5d2a55407000fbf83183fd_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0031.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0030.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0008.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/IMG_7108.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0007.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/IMG_7110.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/New Folder With Items 2/1647393755a2ac2244960cb210dc5a260f7fd73daa_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/IMG_7111.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Conjuntos/C0004.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0036.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Conjuntos/C0001.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Jumpsuit/J0001.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Jumpsuit/IMG_7115 2.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Jumpsuit/J0003.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0038.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Conjuntos/IMG_7132.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0037.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0040.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/IMG_7118 2.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/IMG_7117 2.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/IMG_7121.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Conjuntos/C0003.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Conjuntos/C0010.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Conjuntos/C0011.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Conjuntos/IMG_7124.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/B0019.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Conjuntos/C0008.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Conjuntos/IMG_7130.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Conjuntos/IMG_7133.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Conjuntos/C0002.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Conjuntos/IMG_7137.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Conjuntos/IMG_7136.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0005.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Conjuntos/IMG_7138.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Conjuntos/C0005.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Conjuntos/IMG_7142.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Conjuntos/C0006.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Conjuntos/IMG_7143.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Bolsos/New Folder With Items/1660210000662760010e0f1cd4cfe1af44ca3fb555_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Conjuntos/C0009.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Conjuntos/C0012.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/BO0001.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño niñas/TN004.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/New Folder With Items/IMG_7645.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/IMG_7061.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/PA0004.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño niñas/TN011.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0090.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño niñas/TN010.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/T0005.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño niñas/TN005.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño niñas/TN002.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/BI0012.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0126.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/BI0005.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de abajo/P0020.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/BI0001.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0127.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/1650524831075a24e5ff00197d2fa759c23b18da8f_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Bolsos/A0007.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/T0002.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/T0039.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/IMG_7928.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/New Folder With Items/164549950829909bddf430d1322749b9a986e20415_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/T0004.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/BI0023.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/New Folder With Items/IMG_7626.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/BI0003.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/New Folder With Items/16254470986a9fee91e95443a99f58740eed4ea1c0_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/IMG_7929.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0006.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/New Folder With Items/IMG_7606.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/T0014.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/New Folder With Items/IMG_7625.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/T0029.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/1648873241d45afe0112aea42abca334bddfd692dd_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/167599946553d649a5b145a8fe489ec405fdbe1ee8_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0079.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/New Folder With Items/1610008649df65beade29e6e0d11d1937b767ea0ea_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/V0074_1.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0076.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/V0076_1.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0095.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/New Folder With Items/IMG_7642.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0077.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0091.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/T0016.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/New Folder With Items/739fa431-456f-4a93-a944-7301c1f9fd06.JPG"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/New Folder With Items 2/1662622867fd0cb4026a92412d4822a06efb0a157f_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/T0025.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/T0023.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Bolsos/New Folder With Items/15924623838537c4eca86ef495ebd3fc3b83db97e7_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/New Folder With Items/IMG_7641.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/BI0009.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/T0021.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/New Folder With Items/1606717332ba30c166233627f84f3584e8b8a17211_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/New Folder With Items/IMG_7640.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/New Folder With Items/1610008646be9f3f2ce64399100c41c7ed45679dd0_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/New Folder With Items/IMG_7636.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0017.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0069.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/EP0002.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/EP0001.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/New Folder With Items/IMG_7742.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/New Folder With Items/1616407274c3540988e11d89fabb5544361cefbeae-2.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/New Folder With Items/IMG_7743.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/New Folder With Items/IMG_7631.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/New Folder With Items/IMG_7632.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0018.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de abajo/P0016.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0033.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0072.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/BI0008.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/164748118582376923ea10fde3aa274cc876320f82_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/V0072_1.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/BI0019.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/New Folder With Items/IMG_7629.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/New Folder With Items/IMG_7708.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/BI0028.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/BI0035.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/New Folder With Items/16443075816f09ea1885336e781a64f22db503b89c_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/New Folder With Items/1640227404fa2b4b709e4b448ec47ef9057f0ac631_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/New Folder With Items/IMG_7721.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/New Folder With Items/IMG_7677.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Bolsos/New Folder With Items/1619159641409bddd4e70b2dd7ab7401823531376f_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/New Folder With Items/161407480212cbec0e2f8945be053ee1c974feb4ea_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/New Folder With Items/IMG_7722.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/New Folder With Items/IMG_7613.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Calzado/New Folder With Items/15367435462739260485_thumbnail_900x1199.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/PA0002.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/New Folder With Items/1625447096b2093d25754f078f4105f7114f35e87c_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/PA0007.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/PA0003.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0071.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/New Folder With Items/IMG_7709.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/New Folder With Items/1610008646be9f3f2ce64399100c41c7ed45679dd0_thumbnail_900x-2.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/New Folder With Items/IMG_7611.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/16245907851b78fade8fe44778be63f4d38bf007c0_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/New Folder With Items/IMG_7678.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/PA0006.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Bolsos/New Folder With Items/1611802571025f891400ccc50baa7d9ef2d5e2ca85.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/New Folder With Items/16140748104ccb0f3e6067aff877599985152da411_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0074.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/New Folder With Items/IMG_7725.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Calzado/New Folder With Items/16152645163dd8df5de60c0df37017abc8b9d585c4_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/New Folder With Items/IMG_7595.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Calzado/CA0001.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/New Folder With Items/IMG_7601.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/B0022.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0075.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Bolsos/A0009.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Bolsos/New Folder With Items/159246238648032cb8f384d3605672d11690ca7cde_thumbnail_900x-2.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/New Folder With Items 2/16473937573e778445ca611bcb4eeb3bfd2aace6d1_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0049.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/New Folder With Items/1653386220071343f328f21ab6083360e392d287aa_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/New Folder With Items/IMG_7674.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/New Folder With Items/1634003262d662654010fde2b9f8d51412069cecf4_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/BI0025.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/New Folder With Items/1640227402ea5e4ffd7aee13eb5e751309511b4ed2_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/New Folder With Items 2/16233132666ac984e5438a701d9e51377c30409554_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/New Folder With Items/165292354166d98a3a0954516fde89ee8e7c30af02_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/New Folder With Items/1673231234e8fa62fe87fc29369b1a23bfc6c80591_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/V0056_1.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/SB0004.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/1592447830c6824899bc0e4f1ea90c31bb853b6420_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/1679028617753e55642adbcfebe644df92aa3ea90d_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/New Folder With Items 2/167022357048cc16e2900ec29e2173159e54dde56b_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/SB0002.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/New Folder With Items 2/16626228576344efeada4bb0f87885881b758b36c5_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/New Folder With Items 2/166121894271c4d536e2f8ec3fa707b5587b05d269_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/V0048_1.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0123.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/B0028.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/New Folder With Items 2/1623313273206cbda5241bd2f89f023f5867398f7c_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/164627443153b3ece49d1658ca02b572f4485fa5df_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/B0032.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/B0031.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/New Folder With Items/15918429967de0be5290a7b1d8fb9dccfd17e4c2b1_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0104.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/B0033.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/B0036.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/V0089_1.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Accesorios/New Folder With Items/16472219144bb387147e98196261947a32d776fafd_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0099.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/New Folder With Items/1645499496595fe6233088ca93c3b024aed52712a7_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0122.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/159244784063995ea18d6e0fea9e50cdcf4bafe77d_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/164800332634b0eb073484da49f664e1f9d1760e13_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/1639130635997e9a97285ce51d7a1068eeb0604908_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/1648003329643e3ecde3917ced41e7f85b77932917_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Accesorios/A0012.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/B0037.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/New Folder With Items 2/1660540787b359f41bf0e1463b18126a8de8e9dcd7_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Accesorios/New Folder With Items/1661242703ba6ad1fcfa87ceb32d8b7268b50e97fb_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/V0042_1.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0125.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0042.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/V0044_1.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0044.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/New Folder With Items/167081199167d32fb23ca5c0f747a6d31093d0730c_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/New Folder With Items/1650016312f17b9cfbbf05d6a622a08f4e30bb0990_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/164627443559eb1facb86eadd51702c266ef35690f_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/New Folder With Items/167366050325c4abda0c1cea0882cdb2973d5ae2f4_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0067.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/New Folder With Items/1674020374709da657720cdf7d3ed5c35b87b46823_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/1599531801255d77b025e9024ab50421e2dd21b083_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/1611025499c5b9ca7e2da7c108a3206b225dd6cb48_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8061.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/1610937141b7e631f3774a8c50c19e4a01fbcb618b_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/V0057_1.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0048.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0051.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/V0066_1.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/V0066_2.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0066.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/1611025496f2e2476715c00118182c1ff703de1cff_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/V0063_1.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/V0067_1.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/16109371359106ab44b8f18c344bd2fd9bc15ce7d3_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0111.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de abajo/1630663200c9d3f3106162ecbe9d06d6f698b18cd9_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0059.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/V0051_1.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/1627379676be8f40d69be830c2abd9394066989112_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/V0059_1.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/16319299196f35553fed4a8355c2a08c38f56090ae_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0050.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/165415959850b1faec8c5622557b221c2b6ff37bb5_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/16318628309647a16bfc967185c471f1a348b3fd59_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/1630378501d4196558db659f8947ae45dde776717c_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/New Folder With Items/164543720419b3e21557413e7963a9cd5fe2c361e3_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Calzado/CA0005.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/1591074729931a7d786d4ec7e69c9a765724d72bc7_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de abajo/P0014.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de abajo/P0015.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/V0053_1.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0057.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0053.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/16381516912d60879ac58380da0422ee20e5beb136_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/161093713285fb9055c7f0de459707c1efd0305352_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8064.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/16086391530126ae815c7b2f12190c98a12e62b81b_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/New Folder With Items/16660576303fbb378d0d18988a3d6daae7f1585623_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/New Folder With Items/15918429866cd589785510128f958fd833cd08a434_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/1618449832f8d74fb48da86f7980eb46d488ed9157_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de abajo/164886429316c32ff026a3106893e476a528871136_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8092.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/V0054_1.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de abajo/165327486137ee409c80965a589114f2416d6f6ed3_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/16427330993179a2fca332108d28a1b7a18ae050d0_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0054.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0058.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/V0058_1.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/1648873244ea4812d1102570bbef5d033a5616e206_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/B0046.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/B0040.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Calzado/New Folder With Items/165061825112290db48846ec79f065ff1f9bd6ff01_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Accesorios/New Folder With Items/1648893185e5f2d3991ca4fd651ce21e7e1fee0089_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Accesorios/A0015.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/1647481174efbc74db1914d528e045f4f4ffa58615_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/BO0002.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0082.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0119.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de abajo/P0018.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0081.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0098.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/164868931661c0f74e03731978b14020a2cb6fdde1_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/V0098_1.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Calzado/New Folder With Items/1650618255cbf3ea28b6b4f5dabd41eba01872dc67_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/New Folder With Items/166605762829e0d9b3e4da2eedac43f9f32b2c743d_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8088.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/New Folder With Items/16194143158653f5b1a48a0f25fa6195abf5d36c99_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8093.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8080.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8090.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8089.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0105.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/1642562673e3c0a98668335133390a6f2e10c5a36b_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/New Folder With Items/164543719946f6146c7762be137bece5d3a73e08ab_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/164238545831bbbd7419abcaf4fb2bbbc57dcefcc0_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0112.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0108.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/16425626889dcf0f7fb605ad6735bdf10ca5f9c1a0_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0109.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/New Folder With Items/16261461919ecbbd59996e8a4d1b2e1e1bc013b4d3_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/New Folder With Items 2/16605407906a219c76cc0ab2ac17b9e17dec35cd93_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/New Folder With Items/1644549189d883466804be5fef9743bb253e6ac420_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0103.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/New Folder With Items/16457735502d2e78b45d6cfb5be97432bd736d80b6_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/New Folder With Items/164500219843b77a5a00872645824fbce16f573965_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/1648873241d45afe0112aea42abca334bddfd692dd_thumbnail_900x copy.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0101.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/B0026.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/1647481180ae7ce59ae9c78ae21b7bcd94c26a9e69_thumbnail_900x copy.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0102.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0110.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/164748118582376923ea10fde3aa274cc876320f82_thumbnail_900x copy.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/B0048.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/New Folder With Items/16370307283d488237ff7b75d20a37e1e8bfe9e4d0_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/1646646889bf331202da3d15e78319766b3c5558ee_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0107.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8075.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8094.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/New Folder With Items/1648180569b6f918d99fe58f406e99483fa0901f5e_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/New Folder With Items/16500163100c3ec27b1299bb850ce3b4499f1a64d4_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/16466468964d63730da1236ad35f73c75f4d88c957_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/B0024.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/B0027.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8072.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8060.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8096.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8063.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8062.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8059.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8067.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8058.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8074.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8073.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8066.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8077.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8095.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8078.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8097.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8069.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8070.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8071.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8065.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8081.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8079.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8076.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8083.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8082.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8085.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8084.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8086.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8087.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8091.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8098.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8099.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8100.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8101.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8102.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8103.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8106.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8105.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Trajes de baño/T0022.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8104.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8126.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8107.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8111.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8108.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8115.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8112.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8109 2.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Bolsos/A0010 copy.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8127.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8110.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8138.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8139.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8137.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8118.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8114.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8136.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8113.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8117.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8116.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8119.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8128.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8134.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8135.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8132.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8131.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8120.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/New Folder With Items/IMG_7084.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8130.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_H&M/IMG_8129.jpg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/B0003.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/B0004.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de arriba/B0002.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de abajo/P0021.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/Mas fotos/1644549189d883466804be5fef9743bb253e6ac420_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Partes de abajo/1598948842f8c673bca650d026310a650ecf6d82db_thumbnail_900x.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0011.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Vestidos/V0010.jpeg"
sips -s formatOptions normal "/Users/AAA/Downloads/Letty-UBoutique/whataform-repo/Catalogo UB_Conjuntos/IMG_7149.jpg"